# Generated by Django 4.1 on 2022-08-26 08:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuzdan',
            unique_together={('user', 'para_birimi')},
        ),
    ]
